#!/usr/bin/sh
alias dmenu="dmenu -fn 'UbuntuMono Nerd Font-9' -o 90 -Y 0 -X 500 -h 26 -W 900 -nb '#101010' -nf '#C5C8C6' -sf '#101010' -sb '#72E6CC' -nhb '#101010' -nhf '#72E6CC' -shb '#72E6CC' -shf '#101010'"

declare -a options=(
    "shutdown"
    "reboot"
    "logoff"
    "lock"
    "suspend"
    "abort"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Power Menu:')

if [[ "$choice" == "abort" ]]; then
    exit 0
elif [[ "$choice" == "shutdown" ]]; then
    systemctl poweroff
elif [[ "$choice" == "reboot" ]]; then
    systemctl reboot
elif [[ "$choice" == "logoff" ]]; then
    i3-msg exit
elif [[ "$choice" == "lock" ]]; then
    ~/dev/bash/blurlock
elif [[ "$choice" == "suspend" ]]; then
    systemctl suspend 
else
    exit 1
fi



