#!/usr/bin/sh

alias dmenu="dmenu -fn 'UbuntuMono Nerd Font-9' -o 90 -Y 0 -X 500 -h 26 -W 900 -nb '#101010' -nf '#C5C8C6' -sf '#101010' -sb '#72E6CC' -nhb '#101010' -nhf '#72E6CC' -shb '#72E6CC' -shf '#101010'"
term="kitty"
[[ "$EDITOR" ]] || EDITOR=nvim

declare -a options=(
    "i3 - $HOME/.config/i3/config"
    "nvim - $HOME/.config/nvim"
    "polybar - $HOME/.config/polybar/polybar.ini"
    "dunst - $HOME/.config/dunst/dunstrc"
    "picom - $HOME/.config/picom/picom.conf"
    "scripts - $HOME/dev/bash"
    "ranger - $HOME/.config/ranger"
    "kitty - $HOME/.config/kitty/kitty.conf"
    "fish - $HOME/.config/fish"
    "abort"
)
choice=$(printf '%s\n' "${options[@]}" | awk -F- '{print $1}' | tr -d ' ' | dmenu -i -p 'config')
[[ "$choice" == "abort" ]] && echo "Config dmenu: ok, aborting." && exit 0

for i in "${options[@]}"
do
   : 
   if [[ $(printf '%s\n' "$i" | awk -F- '{print $1}' | tr -d ' ') == "$choice" ]]; then
       choice=$i
   fi
done

cfgfile=$(printf '%s\n' "${choice}" | awk '{print $NF}')
[[ "$choice" ]] && echo "Config dmenu: opening $term -e $EDITOR $cfgfile " && $term -e $EDITOR "$cfgfile" || echo "Config dmenu: nothing? quitting!" && exit 1
