#!/usr/bin/sh
dmenu_run -fn 'UbuntuMono Nerd Font-9' -o 90 -Y 0 -X 500 -h 26 -W 900 -g 3 -l 10 -nb '#101010' -nf '#C5C8C6' -sf '#101010' -sb '#72E6CC' -nhb '#101010' -nhf '#72E6CC' -shb '#72E6CC' -shf '#101010'

