#!/bin/bash

msgTag="mybrightness"
brightness="$(brightnessctl g)"

dunstify -a "changeBrightness" -u low -i display-brightness -h string:x-dunst-stack-tag:$msgTag \
-h int:value:"$brightness" "Brightness: ${brightness}%"

#canberra-gtk-play -i audio-volume-change -d "changeVolume"
