#!/bin/bash

msgTag="myvolume"

volume="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"

if [[ "$mute" == "true" ]]; then
    dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" 
else
    dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "Volume: ${volume}%"
fi

#canberra-gtk-play -i audio-volume-change -d "changeVolume"
