#!/usr/bin/sh

polybar-msg cmd quit
if type "xrandr"; then
    for m in $(polybar --list-monitors | cut -d":" -f1); do
        MONITOR=$m polybar -c=~/.config/polybar/polybar.ini mypolybar &
    done
else
    polybar -c=~/.config/polybar/polybar.ini mypolybar &
fi
echo "Bars launched..."
